export enum RequestedAccessory {

  AUDIO,
  LIGHT_MAIN,
  LIGHT_NIGHT_LIGHT,
  SENSOR_HUMIDITY,
  SENSOR_LUX,
  SENSOR_TEMPERATURE,
  SWITCH_RELAXBREATHE,
  SWITCH_SUNSET,
  SWITCH_WAKE_ALARM,
  SWITCH_WAKE_ALARM_SNOOZE,
  SWITCH_WAKE_ALARM_DISMISS
}
